# Generated by Django 4.0.4 on 2022-05-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=1024)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('field_id_empresa', models.CharField(db_column='_id_empresa', max_length=1024, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=1024)),
                ('telefono_empresa', models.CharField(max_length=30)),
                ('descripcion_empresa', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('numero_identificacion_cliente', models.CharField(max_length=1024)),
                ('precio_factura', models.CharField(max_length=200)),
                ('impuestos_factura', models.CharField(max_length=1024)),
                ('fecha_factura', models.DateField()),
                ('si_factura_recurrente', models.BooleanField()),
                ('fecha_factura_recurrente', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('nombre_inventario', models.CharField(max_length=1024)),
                ('disponibilidad_inventario', models.BooleanField()),
                ('cantidad', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=1024)),
                ('embalaje_pedido', models.CharField(max_length=1024)),
                ('impuestos_pedido', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=1024)),
                ('precio_producto', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('nombre_proovedor', models.CharField(max_length=1024)),
                ('nombre_proovedor2', models.CharField(max_length=1024)),
                ('sede_proovedor', models.CharField(max_length=1024)),
                ('correo_proovedor', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientePedido',
            fields=[
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='miapp.pedido')),
            ],
            options={
                'db_table': 'cliente_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioPedido',
            fields=[
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='miapp.pedido')),
            ],
            options={
                'db_table': 'inventario_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id_proveedor', models.OneToOneField(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='miapp.proveedor')),
            ],
            options={
                'db_table': 'pedido_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id_inventario', models.OneToOneField(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='miapp.inventario')),
            ],
            options={
                'db_table': 'producto_inventario',
                'managed': False,
            },
        ),
    ]
