# Generated by Django 4.0.4 on 2022-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliented',
            fields=[
                ('idcliente', models.IntegerField(db_column='IDCLIENTE', primary_key=True, serialize=False)),
                ('nombre', models.IntegerField(blank=True, db_column='NOMBRE', null=True)),
            ],
            options={
                'db_table': 'CLIENTED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteHasUsuariod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.BigIntegerField(db_column='NMID')),
            ],
            options={
                'db_table': 'CLIENTE_HAS_USUARIOD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturad',
            fields=[
                ('idfactura', models.IntegerField(db_column='IDFACTURA', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='FECHA', null=True)),
            ],
            options={
                'db_table': 'FACTURAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productod',
            fields=[
                ('idproducto', models.IntegerField(db_column='IDPRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('preciounidad', models.TextField(blank=True, db_column='PRECIOUNIDAD', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='STOCK', null=True)),
                ('imagen', models.CharField(blank=True, db_column='IMAGEN', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PRODUCTOD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrod',
            fields=[
                ('idregister', models.IntegerField(db_column='IDREGISTER', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('constot', models.IntegerField(blank=True, db_column='CONSTOT', null=True)),
            ],
            options={
                'db_table': 'REGISTROD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariod',
            fields=[
                ('idusuario', models.IntegerField(db_column='IDUSUARIO', primary_key=True, serialize=False)),
                ('logo', models.CharField(blank=True, db_column='LOGO', max_length=50, null=True)),
                ('documento', models.IntegerField(blank=True, db_column='DOCUMENTO', null=True)),
                ('nombreempresa', models.CharField(blank=True, db_column='NOMBREEMPRESA', max_length=50, null=True)),
                ('correo', models.IntegerField(blank=True, db_column='CORREO', null=True)),
            ],
            options={
                'db_table': 'USUARIOD',
                'managed': False,
            },
        ),
    ]
